### ISSUE TITLE
TOC of namespace start page goes to the top of the sidebar

### ISSUE THREAD

**Issue by my2878452** [my17560/dokuwiki-template-readthedokus#73] opened 2023-12-01 13:45 UTC
Hello!

I've noticed that the TOC of a namespace (or the namespace's start/landing page) always gets displayed at the top of the sidebar instead of below the page, even if the page exists in the TOC.

Take the following example. `Page One` is just a regular page, so its TOC gets displayed right below it, which is ok.

![page_one_ok](https://github.com/my17560/dokuwiki-template-readthedokus/assets/152619980/4278503b-d933-4d3b-8f71-880bd4d5f85a)

`Page Two` is a namespace with a landing page created at `namespace_one:page_two`. Its TOC is displayed at the top of the sidebar, whereas I think it should be below the page name (since it exists in the sidebar). 

![page_two_not_ok](https://github.com/my17560/dokuwiki-template-readthedokus/assets/152619980/ebd3a962-183e-4880-af08-a2f39ba7240f)

In addition to this, there is an issue if I create the landing page at `namespace_one:page_two` instead of `namespace_one:page_two:start`, as the subpages in this namespace don't get displayed in the sidebar when I'm on `namespace_one:page_two`. If I navigate to one of these subpages using the sitemap, they get displayed in the sidebar again. I'm not sure if this is an issue with the template or with the indexmenu plugin.

![page_two_one_ok](https://github.com/my17560/dokuwiki-template-readthedokus/assets/152619980/5bc87728-aafe-480f-ad38-a4d614115032)

When I create a landing page using `:start`, for instance `namespace_one:page_three:start`, the subpages get displayed but the TOC of the landing page is again at the top.

![page_three_not_ok](https://github.com/my17560/dokuwiki-template-readthedokus/assets/152619980/a9399fcf-4a19-422a-957c-089ba8db43f9)

In my sidebar, I have the following:
```
{{indexmenu>..:#1| nojs navbar msort nsort}}

~~NOCACHE~~
```

Could the theme be changed so that the TOC is always shown below the page name (when it exists in the sidebar), regardless of whether it is the landing page of a namespace or not? Thank you in advance.

**Comment by my17560** [comment] 2023-12-02 07:13
Hello.

Could you give me your test files under dokuwiki/data/pages folder? I want to reproduce the situation on my computer.

**Comment by my2878452** [comment] 2023-12-05 11:16
Hello,

Sorry for the late reply. I added the files here.

[readthedokus_test.zip](https://github.com/my17560/dokuwiki-template-readthedokus/files/13559300/readthedokus_test.zip)

Thank you for looking into this.

**Comment by my17560** [comment] 2023-12-06 09:01
Thank you for the test data. I’ve found out the reason  why some TOC are not embedded.

The reason being some TOC menu don’t have “data-wiki-id” attribute. This theme rely on the “data-wiki-id” to embed the TOC. So, It couldn't embed if the menu doesn't have "data-wiki-id". The easiest and preferable fix is to ask IndexMenu author to output “data-wiki-id” on every menu item. If that’s not possible… Let me know I’ll try an another way.

Also, I realized the style for Indexmenu of non-JS version was missing. So I added and committed. "re-install" will update your theme.

The second issue,  the subpages in namespace_one:page_two don't get displayed, this also happens in the default dokuwiki theme. So I guess it’s IndexMenu’s default behavior.

**Comment by my2878452** [comment] 2023-12-06 09:32
Hello! Thank you for looking into this and for the update. I will try to ask the creators of the indexmenu plugin about this.

However, I noted that in their [repository](https://github.com/samuelet/indexmenu) the `data-wiki-id` keyword is never explicitly mentioned. 

Do you know if this is a tag added by the indexmenu plugin or rather by Dokuwiki in the sidebar? Because I noticed that if I just add links in the sidebar page they get tagged automatically with `data-wiki-id`.

Regarding the subpages, this is true, not I see that it also appears in the default template. I can also ask them about this. Thank you!

**Comment by my17560** [comment] 2023-12-07 05:15
I looked into IndexMenu source and you are right, data-wiki-id is added by Dokuwiki, not IndexMenu. If a link is not a namespace then it passes the link to the default Dokuwiki function, however if the link is a namespace then it uses the IndexMenu's function which doesn't append data-wiki-id.

So replacing the line in the file "indexmenu/syntax/indexmenu.php" at line 832 with below fixes this bug. 

```
            $ret .= '<a href="'.wl($link, $more).'" class="'.$tagid.'" data-wiki-id="'. $item['hns'] . '">';
```

**Comment by my17560** [comment] 2024-04-13 08:55
I'm closing this issue since the problem should be fixed by @eduardomozart 's pull request. If you still have any problems, then please feel free to reopen this issue.

**Closed by my17560** 2024-04-13 08:55 UTC
